CRITICAL - 2023-02-24 02:01:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 D:\xampp_new\htdocs\FIMA\app\Controllers\Front.php(41): CodeIgniter\Model->__call('getWhere', Array)
#4 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\Front->index()
#5 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front))
#6 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp_new\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-02-24 02:03:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 D:\xampp_new\htdocs\FIMA\app\Controllers\Front.php(41): CodeIgniter\Model->__call('getWhere', Array)
#4 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\Front->index()
#5 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front))
#6 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp_new\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-02-24 02:03:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 D:\xampp_new\htdocs\FIMA\app\Controllers\Front.php(41): CodeIgniter\Model->__call('getWhere', Array)
#4 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\Front->index()
#5 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front))
#6 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp_new\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-02-24 02:03:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 D:\xampp_new\htdocs\FIMA\app\Controllers\Front.php(41): CodeIgniter\Model->__call('getWhere', Array)
#4 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\Front->index()
#5 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front))
#6 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp_new\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-02-24 02:14:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 D:\xampp_new\htdocs\FIMA\app\Controllers\Front.php(41): CodeIgniter\Model->__call('getWhere', Array)
#4 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\Front->index()
#5 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front))
#6 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp_new\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-02-24 02:14:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2049): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 D:\xampp_new\htdocs\FIMA\app\Controllers\Front.php(41): CodeIgniter\Model->__call('getWhere', Array)
#4 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\Front->index()
#5 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front))
#6 D:\xampp_new\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp_new\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
